repos:
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.5.0
  hooks:
    - id: helm-docs
      args:
        # Make the tool search for charts under the `charts` directory
        - --chart-search-root=charts
        - --output-file=CHART.md
