repos:
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.5.0
  hooks:
    - id: helm-docs
      args:
        # Make the tool search for charts only under the `ethadapter` directory
        - --chart-search-root=ethadapter