apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ethadapter.fullname" . }}
  labels:
    {{- include "ethadapter.labels" . | nindent 4 }}
data:
  rpcAddress: {{ required "config.rpcAddress must be set" .Values.config.rpcAddress | quote }}
  smartContractAddress: {{ include "ethadapter.smartContractAddress" . | quote }}
  smartContractAbi: {{ include "ethadapter.smartContractAbi" . | quote }}