apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ethadapter.fullname" . }}
  annotations:
    "description": "Organisational ETH account and its private key"
  labels:
    {{- include "ethadapter.labels" . | nindent 4 }}
data:
  orgAccountJson: {{ include "ethadapter.orgAccountJson" . | b64enc | quote }}
type: Opaque