apiVersion: v1
kind: Service
metadata:
  name: {{ include "fgt.fullname" . }}-swagger
  labels:
    {{- include "fgt.labels" . | nindent 4 }}
  {{- with .Values.services.swagger.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.swagger.type }}
  ports:
    - port: {{ .Values.services.swagger.port }}
      targetPort: swagger
      protocol: TCP
      name: swagger
  selector:
    {{- include "fgt.selectorLabels" . | nindent 4 }}
