apiVersion: v1
kind: Service
metadata:
  name: {{ include "fgt.fullname" . }}-app
  labels:
    {{- include "fgt.labels" . | nindent 4 }}
  {{- with .Values.services.app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.app.type }}
  ports:
    - port: {{ .Values.services.app.port }}
      targetPort: app
      protocol: TCP
      name: app
  selector:
    {{- include "fgt.selectorLabels" . | nindent 4 }}
