apiVersion: v1
kind: Service
metadata:
  name: {{ include "fgt.fullname" . }}-api
  labels:
    {{- include "fgt.labels" . | nindent 4 }}
  {{- with .Values.services.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.services.api.type }}
  ports:
    - port: {{ .Values.services.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "fgt.selectorLabels" . | nindent 4 }}
