apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartcontract.fullname" . }}-code
  annotations:
    "description": "Required Code for deploying SmartContract"
  labels:
    {{- include "smartcontract.labels" . | nindent 4 }}
data:
  # This function extracts the 'abi' element from the JSON representation of the Smart Contract
  # and writes it to the shared destination
  getAbi.js: |
    function getabi(){
      const fs = require('fs');
      const result = require('fs').readFileSync('./build/contracts/Anchoring.json');
      const jsonResult = JSON.parse(result);
      const abi = JSON.stringify(jsonResult.abi);
      fs.writeFileSync('/container-shared-data/AnchoringAbi.json',abi);
    }
    getabi();
