apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartcontract.configMapNameOrgAccount" . }}
  labels:
    {{- include "smartcontract.labels" . | nindent 4 }}
data:
{{ include "smartcontract.orgAccountData" . | indent 2}}
