apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smartcontract.configMapNameAnchoringSmartContract" . }}
  labels:
    {{- include "smartcontract.labels" . | nindent 4 }}
data:
{{ include "smartcontract.anchoringSmartContractData" . | indent 2}}
