apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "smartcontract.fullname" . }}
rules:
- apiGroups:
  - ""
  resourceNames:
  - {{ include "smartcontract.configMapNameOrgAccount" . | quote }}
  - {{ include "smartcontract.configMapNameAnchoringSmartContract" . | quote }}
  resources:
  - configmaps
  verbs:
  - get
  - create
  - patch
  - update
