apiVersion: v1
kind: Secret
metadata:
  name: {{ include "smartcontract.secretNameOrgAccount" . }}
  labels:
    {{- include "smartcontract.labels" . | nindent 4 }}
data:
{{ include "smartcontract.orgAccountData" . | indent 2}}
type: Opaque