apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epi.configMapSeedsBackupName" . }}
  labels:
    {{- include "epi.labels" . | nindent 4 }}
data:
{{ include "epi.seedsBackupData" . | indent 2}}
