apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epi.fullname" . }}-bdns
  labels:
    {{- include "epi.labels" . | nindent 4 }}
data:
  bdns.hosts: |-
{{ required "config.bdnsHosts must be set" .Values.config.bdnsHosts | indent 4 }}
