apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "epi.fullname" . }}
  labels:
    {{- include "epi.labels" . | nindent 4 }}
data:
  rpcAddress: {{ required "config.rpcAddress must be set" .Values.config.rpcAddress | quote }}
  smartContractAddress: {{ required "config.smartContractAddress must be set" .Values.config.smartContractAddress | quote }}
  smartContractAbi: {{ required "config.smartContractAbi must be set" .Values.config.smartContractAbi | quote }}
