apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "epi.fullname" . }}-init
rules:
- apiGroups:
  - ""
  resourceNames:
  - {{ include "epi.configMapSeedsBackupName" . }}
  resources:
  - configmaps
  verbs:
  - get
  - create
  - patch
  - update
