apiVersion: v1
kind: Secret
metadata:
  name: {{ include "epi.fullname" . }}
  labels:
    {{- include "epi.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.orgAccountJson }}
  orgAccountJson: {{ .Values.secrets.orgAccountJson | b64enc | quote }}
  {{- else }}
  orgAccountJson: {{ required "Either secrets.orgAccountJson or secrets.orgAccountJsonBase64 must be set" .Values.secrets.orgAccountJsonBase64 | quote }}
  {{- end }}
type: Opaque