apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "epi.fullname" . }}-init
  labels:
    {{- include "epi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
